### ISSUE TITLE
can't compress the video

### ISSUE THREAD

**Issue by ThirupathiMukkera** [umeshbsa/ffmpeg-video-compresion-with-progress-android#2]
java.io.IOException: Cannot run program "/data/user/0/com.app.videocompression/files/ffmpeg": error=2, No such file or directory

**Comment by umeshbsa** [comment]
Hi, This api is deprecated till now. Please used an other program

**Comment by MohsinKhanSerpro** [comment]
I am facing same issue
if its deprecated then what program can be use?

**Comment by umeshbsa** [comment]
Hi, FFMPEG has been removed from android, please use silly compression techniques.
